### ISSUE TITLE
Request ?004 - HTML Campaign Modify

### ISSUE THREAD

**Issue by gsiciliani** [MediaLives/advtrade#13]
Nella nuova pagina di template, per la modifica dell'html della campagna, abbiamo detto che ci sono 3 sezioni diverse:
- modifica links sorgenti della campagna
- modifica html tramite editor
- modifica html tramite update totale (upload html)

In questo terzo caso, abbiamo bisogno di fare il reset di tutta la campagna (cancellando i replaced-link vecchi) e creare da zero tutti i replacement dei links nuovi. Contemporaneamente, e' necessario inviare una mail automatica a tutti i publishers che hanno una reservations attiva della campagna in oggetto.

**Comment by hmmedialives** [comment]
mail template ancora da fare

**Comment by hmmedialives** [comment]
save- link reactivate delete
