### ISSUE TITLE
IMG SRC Replace url

### ISSUE THREAD

**Issue by gsiciliani** [MediaLives/advtrade#18]
Tutte le url delle immagini avranno un rewrite "light" nel senso che ogni nuovo url generato avra' un semplice redirect che punta all'immagine sorgente. 

Nel momento in cui si cancella una campagna (o un html), tutti gli url si cancellano dal database e pertanto, se un utente ha ricevuto una mail con dei links gia' rewritati, non riuscira' a vedere niente nella creativita' (anche i pixel di terze parti).

**Comment by hmmedialives** [comment]
Dobbiamo creare un subdomain: come img.adv.email

**Comment by gsiciliani** [comment]
Già creato ieri... Also dns are ok!

**Comment by hmmedialives** [comment]
Thank you.
