### ISSUE TITLE
REMOVE LIMITS OF CAMPAIGN SEARCH

### ISSUE THREAD

**Issue by gsiciliani** [MediaLives/advtrade#23]
In ricerca campagne, togliere il limite di 100 (scrivendo il numero reale di risultato query) ed inserire possibilmente il bottone "others" ogni 50 campagne. In alternativa, facciamo vedere tutte le campagne della query, senza paginazione.

**Comment by gsiciliani** [comment]
troppo lento :(
ci vorrebbe un **loader** in mezzo alla pagina, durante l'attesa....

**Comment by hmmedialives** [comment]
ho messo pagination. adesso veloce
